version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123GGGhhh123
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123GGGhhh123
    ports:
      - "8081:8081"